### ISSUE TITLE
PHP Warning: Undefined array key "rootLevel"

### ISSUE THREAD

**Issue by stekna** [sudhaus7/typo3-xlsimport#23] opened 2023-02-03 19:38 UTC
TYPO3 11.5.22
PHP 8.0 or 8.1
Installed with EM.

I get the error:
`(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "rootLevel" in /www/htdocs/typo3conf/ext/xlsimport/Classes/Controller/XlsimportController.php line 144`

**Comment by calien666** [comment] 2023-02-11 05:10
New release 4.0 is now failsafe to this after refactoring the access handling. Please describe a feedback and close the issue, if the error doesn't appear anymore.

**Comment by schmitzal** [comment] 2023-03-24 16:29
Same here. 

Updated to v. 4.0. The first mentioned exception is gone but once I execute an import, the last mentioned exception is thrown.
I tried to workaround it by setting the hook array empty in my project extension.

After that the next exception is thrown:
```
PHP Warning: Undefined array key "pid" in /var/www/html/project/web/typo3/sysext/core/Classes/DataHandling/DataHandler.php line 930
```

**Comment by calien666** [comment] 2023-03-24 16:31
Okay, I'll make some code cleanups and run with testing tools and phpstan, do identify and clear php-8 related errors. Please give me some days, I hope, until Sunday I will get a new version working.

**Comment by calien666** [comment] 2023-03-26 03:03
> ```
> PHP Warning: Undefined array key "pid" in /var/www/html/project/web/typo3/sysext/core/Classes/DataHandling/DataHandler.php line 930
> ```

The Hook problem mentioned above was easy. But according to this issue I need more information, as the pid is set explicitly, if not set in datasets already.

**Comment by schmitzal** [comment] 2023-03-26 10:18
Example CSV data (anonymized) I get from the customer to import redirects:

```
https://www.domain.com;/my/url/1;t3://page?uid=1
https://www.domain.com;/my/url/2;t3://page?uid=2
;;
;;
;;
;;
;;
```

Than I map the 3 columns to their column in DB.
And after resolving the hook problem, I end having this "pid" error.

For the extension there is only this configured:
`module.tx_xlsimport.settings.allowedTables = sys_redirect`

**Comment by deadmanIsARabbit** [comment] 2023-03-31 14:35
> The Hook problem mentioned above was easy. 

Would you mind to push your fix?  Please. :)

**Comment by schmitzal** [comment] 2023-04-05 15:58
Just looked more into this and noticed, that the exception with the "pid" is thrown, when you haven't selected any page in the pagetree, so `_GP('id')` is null.
Maybe there is a check needed initially, before allowing to upload something for import?

**Comment by calien666** [comment] 2024-02-08 20:00
The issue is quickfixed in latest version.

**Closed by calien666** 2024-02-08 20:00 UTC
Labels: bug
